# See https://github.com/actions/labeler/tree/main for more information about the labeler action

translations:
  - changed-files:
      - any-glob-to-any-file: packages/studiocms_core/src/i18n/translations/*