# See https://github.com/actions/labeler/tree/main for more information about the labeler action

translations:
  - changed-files:
      - any-glob-to-any-file:
          - packages/studiocms/src/virtuals/i18n/translations/*
          - packages/studiocms/src/handlers/plugin-i18n/*
          - packages/studiocms/src/plugins/analytics/i18n/*
