"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "/packages/studiocms/src/lib/i18n/translations/en-us.json",
    "translation": "/packages/studiocms/src/lib/i18n/translations/%two_letters_code%.json"
  }
]