catalog:
  "@types/node": ^22.0.0
  arctic: ^3.7.0
  astro-integration-kit: ^0.19.0
  chalk: ^5.6.0
  deepmerge-ts: ^7.1.5
  esbuild: ^0.25.8
  sharp: ^0.34.3
  tinyglobby: ^0.2.14
  typescript: ^5.9.2
  nodemailer: ^7.0.5
  "@types/nodemailer": ^7.0.1

catalogs:
  astrojs:
    "@astrojs/db": ^0.17.1
    "@astrojs/rss": ^4.0.12
    "@astrojs/check": ^0.9.4
    "@astrojs/node": ^9.4.2
    astro: ^5.13.2
    vite: ^6.3.4
  effect:
    "@effect/cli": ^0.69.2
    "@effect/cluster": ^0.48.2
    "@effect/experimental": ^0.54.6
    "@effect/language-service": ^0.35.2
    "@effect/platform": ^0.90.6
    "@effect/platform-node": ^0.96.0
    "@effect/printer": ^0.45.0
    "@effect/printer-ansi": ^0.45.0
    "@effect/rpc": ^0.69.1
    "@effect/sql": ^0.44.2
    "@effect/typeclass": ^0.36.0
    "@effect/workflow": ^0.9.2
    effect: ^3.17.9
  min:
    "@astrojs/db": ^0.17.1
    "@astrojs/markdown-remark": ^6.3.3
    "@libsql/client": ^0.15.10
    "@studiocms/web-vitals": ^4.4.1
    astro: ^5.12.9
    drizzle-orm: ^0.42.0
    vite: ^6.3.4
  react:
    "@astrojs/react": ^4.3.0
    "@types/react": ^19.1.10
    "@types/react-dom": ^19.1.7
    react: ^19.1.1
    "react-dom": ^19.1.1
  studiocms:
    "@studiocms/markdown-remark-processor": ^1.2.0
    "@studiocms/ui": ^0.4.17
    "@studiocms/web-vitals": ^4.5.0
    "@withstudiocms/cli-kit": ^0.1.0

packages:
  - "packages/@studiocms/*"
  - "packages/@withstudiocms/*"
  - "packages/*"
  - "playground"
