catalog: # Confirmed Current Master Catalog - 11.01.2024
  '@astrojs/db': ^0.14.6
  '@astrojs/rss': ^4.0.11
  '@astrojs/react': ^4.2.0
  '@astrojs/check': ^0.9.4
  '@astrojs/tailwind': ^5.1.2
  '@astrojs/starlight': ^0.30
  '@astrojs/web-vitals': ^3.0.1
  '@astrojs/node': ^9.0.1
  '@types/node': ^20.14.11
  "@studiocms/ui": ^0.4.10
  "@sentry/astro": ^8.45.0
  astro: ^5.3.0
  astro-integration-kit: ^0.18
  astro-theme-provider: ^0.7.0
  sharp: ^0.33.5
  typescript: ^5.7
  vite: ^6.0.5

catalogs:
  min: # Confirmed Current Min Deps - 11.01.2024
    astro: ^5.2.0
    '@astrojs/db': ^0.14.6
    '@astrojs/markdown-remark': ^6.1.0
    vite: ^6.0

packages:
  - "packages/*"
  - "playground"
  - "docs"
  - "build-scripts"
