packages:
  - packages/@studiocms/*
  - packages/@withstudiocms/*
  - packages/@withstudiocms/*/test/fixtures/*
  - packages/*
  - bundle-tests/*
  - playground

catalog:
  "@codecov/astro-plugin": ^1.9.1
  "@types/mdast": ^4.0.4
  "@types/node": ^22.0.0
  arctic: ^3.7.0
  astro-integration-kit: ^0.19.1
  chalk: ^5.6.2
  deepmerge-ts: ^7.1.5
  esbuild: ^0.25.8
  sharp: ^0.34.3
  tinyglobby: ^0.2.15
  typescript: ^5.9.3

catalogs:
  astrojs:
    "@astrojs/check": ^0.9.5
    "@astrojs/db": ^0.18.2
    "@astrojs/node": ^9.5.0
    "@astrojs/rss": ^4.0.13
    astro: ^5.15.4
    vite: ^6.3.4
  effect:
    "@effect/cli": ^0.72.1
    "@effect/platform": ^0.93.3
    "@effect/platform-node": ^0.100.0
    effect: ^3.19.4
  min:
    "@astrojs/markdown-remark": ^6.3.3
    "@libsql/client": ^0.15.10
    "@studiocms/web-vitals": ^4.5.3
    astro: ^5.12.9
    drizzle-orm: ^0.42.0
    vite: ^6.3.4
  react:
    "@astrojs/react": ^4.4.2
    "@types/react": ^19.2.5
    "@types/react-dom": ^19.2.3
    react: ^19.2.0
    react-dom: ^19.2.0
  studiocms:
    "@studiocms/markdown-remark-processor": ^1.2.0
    "@studiocms/ui": ^1.0.0-beta.4
    "@studiocms/web-vitals": ^4.5.3
    "@withstudiocms/cli-kit": ^0.1.0

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - studiocms
  - "@studiocms/*"
  - "@withstudiocms/*"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - canvas
  - esbuild
  - msgpackr-extract
  - sharp
