catalog: # Confirmed Current Master Catalog - 11.01.2024
  '@astrojs/db': ^0.14.3
  '@astrojs/markdown-remark': ^5.2.0
  '@astrojs/rss': ^4.0.7
  '@astrojs/react': ^3.6.3
  '@astrojs/check': ^0.9.4
  '@astrojs/tailwind': ^5.1.2
  '@astrojs/starlight': ^0.29.2
  '@astrojs/web-vitals': ^3.0.0
  '@astrojs/node': ^8.3.4
  '@types/node': ^20.14.11
  "@studiocms/ui": ^0.1.0
  astro: ^4.16.14
  astro-integration-kit: ^0.16.1
  astro-theme-provider: ^0.6.1
  sharp: ^0.33.4
  typescript: ^5.6.3
  vite: ^5.4.8

catalogs:
  peer-robots: # Peer Dependencies for @studiocms/robotstxt - 12.06.2024
    astro: ^4.16 || ^5

  min: # Confirmed Current Min Deps - 11.01.2024
    astro: ">=4.16"
    '@astrojs/db': ">=0.14.2"
    astro-integration-kit: ">=0.16"
    vite: ^4 || ^5

  landing: # Confirmed Current Landing Deps - 11.01.2024
    motion: ^10.18.0
    tailwindcss: ^3.4.14
    tailwind-merge: ^2.5.4
    tailwind-scrollbar: ^3.1.0
    '@tailwindcss/typography': ^0.5.15
    astro-icon: ^1.1.1
    '@resvg/resvg-js': ^2.6.2
    html-entities: ^2.5.2
    satori: ^0.11.1
    satori-html: ^0.3.2

  docs: # Confirmed Current Docs Deps - 11.01.2024
    "@11ty/eleventy-fetch": ^4.0.1
    "@lorenzo_lewis/starlight-utils": ^0.2.0
    "@types/hast": ^3.0.4
    astro-embed: ^0.7.4
    hast: ^1.0.0
    hast-util-select: ^6.0.3
    p-retry: ^6.2.0
    rehype: ^13.0.2
    starlight-typedoc: ^0.16.0
    typedoc: ^0.26.10
    typedoc-plugin-markdown: ^4.2.9
    starlight-image-zoom: ^0.8.0
    hastscript: ^9.0.0
    hast-util-to-string: ^3.0.1
    mdast-util-from-markdown: ^2.0.1
    mdast-util-gfm: ^3.0.0
    mdast-util-to-hast: ^13.2.0
    rehype-slug: ^6.0.0
    rehype-autolink-headings: ^7.1.0
    rehype-external-links: ^3.0.0
    "@types/html-escaper": ^3.0.2
    html-escaper: ^3.0.3
    expressive-code-twoslash: ^0.3.0
    "@shikijs/colorized-brackets": ^1.23.1
    starlight-package-managers: ^0.8.0

  studiocms: # Confirmed Current CMS Deps - 11.01.2024
    '@types/semver': ^7.5.8
    package-json: ^10.0.1
    semver: ^7.6.3

  studiocms-core: # Confirmed Current Core Deps - 11.01.2024
    remark-rehype: ^11.1.0
    mdast-util-to-hast: ^13.2.0
    mrmime: ^2.0.0
    unified: ^11.0.5

  studiocms-devapps: # Confirmed Current DevApps Deps - 11.01.2024
    "@libsql/client": ^0.14.0
    "@types/cheerio": ^0.22.35
    "@types/turndown": ^5.0.5
    cheerio: ^1.0.0
    turndown: ^7.2.0
    html-entities: ^2.5.2

  studiocms-auth: # Confirmed Current Auth Deps - 11.01.2024
    '@oslojs/crypto': ^1.0.1
    '@oslojs/encoding': ^1.1.0
    '@oslojs/binary': ^1.0.0
    '@types/three': 0.169.0
    arctic: ^2.0.1
    three: 0.170.0
    
  studiocms-shared: # Confirmed Current Shared Deps - 11.01.2024
    '@fontsource-variable/onest': 5.1.0
    '@inox-tools/runtime-logger': ^0.3.4
    '@iconify-json/heroicons': ^1.2.1
    "@matthiesenxyz/astrodtsbuilder": ^0.1.2
    "@matthiesenxyz/integration-utils": ^0.2.0
    rollup-plugin-copy: ^3.5.0

  studiocms-renderer: # Confirmed Current Renderer Deps - 11.01.2024
    "@mdx-js/mdx": ^3.0.1
    '@markdoc/markdoc': ^0.4.0
    "@types/react": ^18.3.5
    "@types/react-dom": ^18.3.0
    react: ^18.3.1
    react-dom: ^18.3.1
    remark-gfm: ^4.0.0
    rehype-highlight: ^7.0.0

  studiocms-imagehandler: # Confirmed Current ImageHandler Deps - 11.01.2024
    '@cloudinary/url-gen': ^1.21.0

packages:
  - "packages/*"
  - "playground"
  - "docs"
