catalog:
  '@astrojs/db': ^0.14.8
  '@astrojs/rss': ^4.0.11
  '@astrojs/react': ^4.2.1
  '@astrojs/check': ^0.9.4
  '@astrojs/starlight': ^0.32.1
  '@astrojs/web-vitals': ^3.0.1
  '@astrojs/node': ^9.1.2
  '@types/node': ^22.0.0
  "@studiocms/ui": ^0.4.16
  "@sentry/astro": ^9.2.0
  astro: ^5.4.3
  astro-integration-kit: ^0.18
  sharp: ^0.33.5
  typescript: ^5.7
  vite: ^6.2.0

catalogs:
  min:
    astro: ^5.4.3
    '@astrojs/db': ^0.14.7
    '@astrojs/markdown-remark': ^6.2.1
    vite: ^6.2.0

packages:
  - "packages/*"
  - "playground"
  - "build-scripts"
