catalog:
  '@astrojs/db': ^0.15
  '@astrojs/rss': ^4.0.11
  '@astrojs/react': ^4.2.1
  '@astrojs/check': ^0.9.4
  '@astrojs/node': ^9.1.3
  '@types/node': ^22.0.0
  "@studiocms/ui": ^0.4.16
  "@sentry/astro": ^9.2.0
  '@studiocms/web-vitals': ^4.1.1
  astro: ^5.9
  astro-integration-kit: ^0.18
  sharp: ^0.34.0
  typescript: ^5.8.2
  vite: ^6.3.4

catalogs:
  min:
    astro: ^5.9
    '@astrojs/db': ^0.15
    '@astrojs/markdown-remark': ^6.3.1
    vite: ^6.3.4
  effect:
    effect: ^3.17.3
    '@effect/cli': ^0.69.0
    '@effect/platform': ^0.90.0
    '@effect/platform-node': ^0.94.0
    '@effect/language-service': ^0.31.2
    
packages:
  - "packages/@studiocms/*"
  - "packages/@withstudiocms/*"
  - "packages/*"
  - "playground"
