catalog:
  "@types/node": ^22.0.0
  arctic: ^3.7.0
  astro-integration-kit: ^0.18
  deepmerge-ts: ^7.1.5
  esbuild: ^0.25.8
  sharp: ^0.34.3
  typescript: ^5.8.3

catalogs:
  astrojs:
    "@astrojs/db": ^0.16.1
    "@astrojs/rss": ^4.0.12
    "@astrojs/check": ^0.9.4
    "@astrojs/node": ^9.3.3
    astro: ^5.12.8
    vite: ^6.3.4
  effect:
    "@effect/cli": ^0.69.0
    "@effect/cluster": ^0.46.2
    "@effect/experimental": ^0.54.3
    "@effect/language-service": ^0.31.2
    "@effect/platform": ^0.90.0
    "@effect/platform-node": ^0.94.1
    "@effect/printer": ^0.45.0
    "@effect/printer-ansi": ^0.45.0
    "@effect/rpc": ^0.68.2
    "@effect/sql": ^0.44.0
    "@effect/typeclass": ^0.36.0
    "@effect/workflow": ^0.8.1
    effect: ^3.17.6
  min:
    "@astrojs/db": ^0.16.1
    "@astrojs/markdown-remark": ^6.3.3
    "@libsql/client": ^0.15.10
    "@studiocms/web-vitals": ^4.3.0
    astro: ^5.12.8
    drizzle-orm: ^0.42.0
    vite: ^6.3.4
  react:
    "@astrojs/react": ^4.3.0
    "@types/react": ^19.1.9
    "@types/react-dom": ^19.1.7
    react: ^19.1.1
    "react-dom": ^19.1.1
  studiocms:
    "@studiocms/markdown-remark-processor": ^1.2.0
    "@studiocms/ui": ^0.4.17
    "@studiocms/web-vitals": ^4.3.0
    "@withstudiocms/cli-kit": ^0.1.0

packages:
  - "packages/@studiocms/*"
  - "packages/@withstudiocms/*"
  - "packages/*"
  - "playground"
