catalog:
  '@astrojs/db': ^0.14.14
  '@astrojs/rss': ^4.0.11
  '@astrojs/react': ^4.2.1
  '@astrojs/check': ^0.9.4
  '@astrojs/web-vitals': ^3.0.2
  '@astrojs/node': ^9.1.3
  '@types/node': ^22.0.0
  "@studiocms/ui": ^0.4.16
  "@sentry/astro": ^9.2.0
  astro: ^5.7.12
  astro-integration-kit: ^0.18
  sharp: ^0.34.0
  typescript: ^5.8.2
  vite: ^6.3.4

catalogs:
  min:
    astro: ^5.7.12
    '@astrojs/db': ^0.14.14
    '@astrojs/markdown-remark': ^6.3.1
    vite: ^6.2.6
  effect:
    effect: ^3.16.3
    '@effect/platform': ^0.84.6
    '@effect/platform-browser': ^0.64.6
    '@effect/platform-node': ^0.85.2
    '@effect/platform-node-shared': ^0.39.2
    '@effect/language-service': ^0.18.0
    
packages:
  - "packages/*"
  - "playground"
