catalog:
  "@types/node": ^22.0.0
  arctic: ^3.7.0
  astro-integration-kit: ^0.19.0
  chalk: ^5.6.2
  deepmerge-ts: ^7.1.5
  esbuild: ^0.25.8
  sharp: ^0.34.3
  tinyglobby: ^0.2.15
  typescript: ^5.9.2
  "@types/mdast": ^4.0.4
  "@codecov/astro-plugin": ^1.9.1

catalogs:
  astrojs:
    "@astrojs/db": ^0.18.0
    "@astrojs/rss": ^4.0.12
    "@astrojs/check": ^0.9.4
    "@astrojs/node": ^9.4.4
    astro: ^5.13.10
    vite: ^6.3.4
  effect:
    "@effect/cli": ^0.69.2
    "@effect/platform": ^0.90.10
    "@effect/platform-node": ^0.96.1
    effect: ^3.17.14
  min:
    "@astrojs/markdown-remark": ^6.3.3
    "@libsql/client": ^0.15.10
    "@studiocms/web-vitals": ^4.5.3
    astro: ^5.12.9
    drizzle-orm: ^0.42.0
    vite: ^6.3.4
  react:
    "@astrojs/react": ^4.3.1
    "@types/react": ^19.1.13
    "@types/react-dom": ^19.1.9
    react: ^19.1.1
    "react-dom": ^19.1.1
  studiocms:
    "@studiocms/markdown-remark-processor": ^1.2.0
    "@studiocms/ui": ^1.0.0-beta.1
    "@studiocms/web-vitals": ^4.5.3
    "@withstudiocms/cli-kit": ^0.1.0

packages:
  - "packages/@studiocms/*"
  - "packages/@withstudiocms/*"
  - "packages/@withstudiocms/*/test/fixtures/*"
  - "packages/*"
  - "bundle-tests/*"
  - "playground"

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - studiocms
  - '@studiocms/*'
  - '@withstudiocms/*'
