name: Run Effect Diagnostics
description: This action runs Effect diagnostics for specified commands.

inputs:
  cmd:
    description: "The command to run effect diagnostics for."
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Tools & Dependencies
      uses: withstudiocms/automations/.github/actions/install@f286863f2f7a414794b9a10ee6f1cadbb07f722f # main

    - name: run Build for Effect Diagnostics
      shell: bash
      run: pnpm ci:build

    - name: Run ${{ inputs.cmd }} Effect Diagnostics
      shell: bash
      run: | # zizmor: ignore[template-injection]
        pnpm ci:effect-check:${{ inputs.cmd }}
