import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';

const rendererMarkdownConfig = DTSBuilder();

rendererMarkdownConfig.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

rendererMarkdownConfig.addModule('studiocms:renderer/astroMarkdownConfig', {
	defaultExport: {
		typeDef: `import('astro').AstroUserConfig['markdown']`,
	},
});

const rendererMarkdownConfigDTS = rendererMarkdownConfig.makeAstroInjectedType(
	'astroMarkdownConfig.d.ts'
);

export default rendererMarkdownConfigDTS;
