import type { tsPageDataCategoriesSelect, tsPageDataTagsSelect } from 'studiocms:sdk/types';

// Mock data for categories
export const mockCategories: tsPageDataCategoriesSelect[] = [
	{
		id: 1,
		name: 'Technology',
		parent: null,
		description: 'Technology-related content and articles',
		slug: 'technology',
		meta: { color: '#3b82f6', icon: 'cpu' },
	},
	{
		id: 2,
		name: 'Web Development',
		parent: 1,
		description: 'Web development tutorials and guides',
		slug: 'web-development',
		meta: { color: '#8b5cf6', icon: 'code' },
	},
	{
		id: 3,
		name: 'Frontend',
		parent: 2,
		description: 'Frontend frameworks and libraries',
		slug: 'frontend',
		meta: { color: '#06b6d4', icon: 'window' },
	},
	{
		id: 4,
		name: 'Backend',
		parent: 2,
		description: 'Backend development and APIs',
		slug: 'backend',
		meta: { color: '#10b981', icon: 'server' },
	},
	{
		id: 5,
		name: 'Design',
		parent: null,
		description: 'Design principles and UI/UX',
		slug: 'design',
		meta: { color: '#ec4899', icon: 'palette' },
	},
	{
		id: 6,
		name: 'DevOps',
		parent: 1,
		description: 'DevOps practices and tools',
		slug: 'devops',
		meta: { color: '#f59e0b', icon: 'cog' },
	},
	{
		id: 7,
		name: 'Mobile',
		parent: 1,
		description: 'Mobile app development',
		slug: 'mobile',
		meta: { color: '#ef4444', icon: 'device-mobile' },
	},
	{
		id: 8,
		name: 'Tutorials',
		parent: null,
		description: 'Step-by-step tutorials and guides',
		slug: 'tutorials',
		meta: { color: '#14b8a6', icon: 'book-open' },
	},
];

// Mock data for tags
export const mockTags: tsPageDataTagsSelect[] = [
	{
		id: 1,
		name: 'JavaScript',
		description: 'JavaScript programming language',
		slug: 'javascript',
		meta: { color: '#f7df1e' },
	},
	{
		id: 2,
		name: 'TypeScript',
		description: 'TypeScript superset of JavaScript',
		slug: 'typescript',
		meta: { color: '#3178c6' },
	},
	{
		id: 3,
		name: 'React',
		description: 'React JavaScript library',
		slug: 'react',
		meta: { color: '#61dafb' },
	},
	{
		id: 4,
		name: 'Astro',
		description: 'Astro web framework',
		slug: 'astro',
		meta: { color: '#ff5d01' },
	},
	{
		id: 5,
		name: 'CSS',
		description: 'Cascading Style Sheets',
		slug: 'css',
		meta: { color: '#264de4' },
	},
	{
		id: 6,
		name: 'Node.js',
		description: 'Node.js runtime environment',
		slug: 'nodejs',
		meta: { color: '#339933' },
	},
	{
		id: 7,
		name: 'API',
		description: 'Application Programming Interface',
		slug: 'api',
		meta: { color: '#009688' },
	},
	{
		id: 8,
		name: 'Database',
		description: 'Database design and management',
		slug: 'database',
		meta: { color: '#ff6f00' },
	},
	{
		id: 9,
		name: 'Security',
		description: 'Security best practices',
		slug: 'security',
		meta: { color: '#d32f2f' },
	},
	{
		id: 10,
		name: 'Performance',
		description: 'Performance optimization',
		slug: 'performance',
		meta: { color: '#7cb342' },
	},
	{
		id: 11,
		name: 'Testing',
		description: 'Testing and quality assurance',
		slug: 'testing',
		meta: { color: '#e91e63' },
	},
	{
		id: 12,
		name: 'Docker',
		description: 'Docker containerization',
		slug: 'docker',
		meta: { color: '#2496ed' },
	},
	{
		id: 13,
		name: 'Git',
		description: 'Git version control',
		slug: 'git',
		meta: { color: '#f05032' },
	},
	{
		id: 14,
		name: 'UI/UX',
		description: 'User interface and experience design',
		slug: 'ui-ux',
		meta: { color: '#9c27b0' },
	},
	{
		id: 15,
		name: 'Accessibility',
		description: 'Web accessibility standards',
		slug: 'accessibility',
		meta: { color: '#4caf50' },
	},
];
