import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver } from 'astro-integration-kit';

const { resolve } = createResolver(import.meta.url);

const dtsFile = DTSBuilder();

dtsFile.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

dtsFile.addModule('studiocms:config', {
	defaultExport: {
		typeDef: `import('${resolve('../schemas/config/index.ts')}').StudioCMSConfig`,
	},
	namedExports: [
		{
			name: 'config',
			typeDef: `import('${resolve('../schemas/config/index.ts')}').StudioCMSConfig`,
		},
		{
			name: 'dashboardConfig',
			typeDef: `import('${resolve('../schemas/config/index.ts')}').StudioCMSConfig['dashboardConfig']`,
		},
		{
			name: 'AuthConfig',
			typeDef: `import('${resolve('../schemas/config/index.ts')}').StudioCMSConfig['dashboardConfig']['AuthConfig']`,
		},
		{
			name: 'developerConfig',
			typeDef: `import('${resolve('../schemas/config/index.ts')}').StudioCMSConfig['dashboardConfig']['developerConfig']`,
		},
		{
			name: 'defaultFrontEndConfig',
			typeDef: `import('${resolve('../schemas/config/index.ts')}').StudioCMSConfig['defaultFrontEndConfig']`,
		},
	],
});

dtsFile.addModule('studiocms:version', {
	defaultExport: {
		typeDef: 'string',
	},
});

export const coreDtsFileOutput = dtsFile.makeAstroInjectedType('core.d.ts');

export default coreDtsFileOutput;
