import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver } from 'astro-integration-kit';

const { resolve } = createResolver(import.meta.url);

const sdkDTS = DTSBuilder();

sdkDTS.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

sdkDTS.addModule('studiocms:sdk', {
	defaultExport: {
		typeDef: `typeof import('${resolve('../sdk-utils/index.ts')}').default`,
	},
});

sdkDTS.addModule('studiocms:sdk/get', {
	defaultExport: {
		typeDef: `typeof import('${resolve('../sdk-utils/get/index.ts')}').default`,
	},
});

sdkDTS.addModule('studiocms:sdk/post', {
	defaultExport: {
		typeDef: `typeof import('${resolve('../sdk-utils/post/index.ts')}').default`,
	},
});

sdkDTS.addModule('studiocms:sdk/update', {
	defaultExport: {
		typeDef: `typeof import('${resolve('../sdk-utils/update/index.ts')}').default`,
	},
});

sdkDTS.addModule('studiocms:sdk/delete', {
	defaultExport: {
		typeDef: `typeof import('${resolve('../sdk-utils/delete/index.ts')}').default`,
	},
});

sdkDTS.addModule('studiocms:sdk/auth', {
	defaultExport: {
		typeDef: `typeof import('${resolve('../sdk-utils/auth/index.ts')}').default`,
	},
});

sdkDTS.addModule('studiocms:sdk/types', {
	typeExports: [
		{
			name: 'STUDIOCMS_SDK',
			typeDef: `import('${resolve('../sdk-utils/types/index.ts')}').STUDIOCMS_SDK`,
		},
	],
});

export const sdkDtsFile = sdkDTS.makeAstroInjectedType('sdk.d.ts');
