import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';

const dtsFile = DTSBuilder();

dtsFile.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

dtsFile.addModule('studiocms:changelog', {
	defaultExport: {
		typeDef: 'string',
	},
});

export const changelogDtsFileOutput = dtsFile.makeAstroInjectedType('changelog.d.ts');

export default changelogDtsFileOutput;
