import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver } from 'astro-integration-kit';

const { resolve } = createResolver(import.meta.url);

const dtsFile = DTSBuilder();

dtsFile.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

dtsFile.addModule('studiocms:lib', {
	namedExports: [
		{
			name: 'HeadConfigSchema',
			typeDef: `typeof import('${resolve('../lib/head.js')}').HeadConfigSchema`,
		},
		{
			name: 'createHead',
			typeDef: `typeof import('${resolve('../lib/head.js')}').createHead`,
		},
		{
			name: 'headDefaults',
			typeDef: `typeof import('${resolve('../lib/headDefaults.js')}').headDefaults`,
		},
		{
			name: 'stringify',
			typeDef: `typeof import('${resolve('../lib/jsonUtils.js')}').stringify`,
		},
		{
			name: 'stringifyMap',
			typeDef: `typeof import('${resolve('../lib/jsonUtils.js')}').stringifyMap`,
		},
		{
			name: 'pathWithBase',
			typeDef: `typeof import('${resolve('../lib/pathGenerators.js')}').pathWithBase`,
		},
		{
			name: 'fileWithBase',
			typeDef: `typeof import('${resolve('../lib/pathGenerators.js')}').fileWithBase`,
		},
		{
			name: 'ensureLeadingSlash',
			typeDef: `typeof import('${resolve('../lib/pathGenerators.js')}').ensureLeadingSlash`,
		},
		{
			name: 'ensureTrailingSlash',
			typeDef: `typeof import('${resolve('../lib/pathGenerators.js')}').ensureTrailingSlash`,
		},
		{
			name: 'ensureLeadingSlashAndTrailingSlash',
			typeDef: `typeof import('${resolve('../lib/pathGenerators.js')}').ensureLeadingSlashAndTrailingSlash`,
		},
		{
			name: 'stripLeadingSlash',
			typeDef: `typeof import('${resolve('../lib/pathGenerators.js')}').stripLeadingSlash`,
		},
		{
			name: 'stripTrailingSlash',
			typeDef: `typeof import('${resolve('../lib/pathGenerators.js')}').stripTrailingSlash`,
		},
		{
			name: 'stripLeadingSlashAndTrailingSlash',
			typeDef: `typeof import('${resolve('../lib/pathGenerators.js')}').stripLeadingSlashAndTrailingSlash`,
		},
		{
			name: 'stripHtmlExtension',
			typeDef: `typeof import('${resolve('../lib/pathGenerators.js')}').stripHtmlExtension`,
		},
		{
			name: 'ensureHtmlExtension',
			typeDef: `typeof import('${resolve('../lib/pathGenerators.js')}').ensureHtmlExtension`,
		},
		{
			name: 'removeLeadingTrailingSlashes',
			typeDef: `typeof import('${resolve('../lib/removeLeadingTrailingSlashes.js')}').removeLeadingTrailingSlashes`,
		},
		{
			name: 'getSluggedRoute',
			typeDef: `typeof import('${resolve('../lib/routeMap.js')}').getSluggedRoute`,
		},
		{
			name: 'getEditRoute',
			typeDef: `typeof import('${resolve('../lib/routeMap.js')}').getEditRoute`,
		},
		{
			name: 'getDeleteRoute',
			typeDef: `typeof import('${resolve('../lib/routeMap.js')}').getDeleteRoute`,
		},
		{
			name: 'makeNonDashboardRoute',
			typeDef: `typeof import('${resolve('../lib/routeMap.js')}').makeNonDashboardRoute`,
		},
		{
			name: 'makeDashboardRoute',
			typeDef: `typeof import('${resolve('../lib/routeMap.js')}').makeDashboardRoute`,
		},
		{
			name: 'StudioCMSRoutes',
			typeDef: `typeof import('${resolve('../lib/routeMap.js')}').StudioCMSRoutes`,
		},
		{
			name: 'sideBarLinkMap',
			typeDef: `typeof import('${resolve('../lib/routeMap.js')}').sideBarLinkMap`,
		},
		{
			name: 'urlGenFactory',
			typeDef: `typeof import('${resolve('../lib/urlGen.js')}').urlGenFactory`,
		},
	],
	typeExports: [
		{
			name: 'HeadConfig',
			typeDef: `import('${resolve('../lib/head.js')}').HeadConfig`,
		},
		{
			name: 'HeadUserConfig',
			typeDef: `import('${resolve('../lib/head.js')}').HeadUserConfig`,
		},
	],
});

export const libDtsFileOutput = dtsFile.makeAstroInjectedType('lib.d.ts');

export default libDtsFileOutput;
