import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver } from 'astro-integration-kit';

const { resolve } = createResolver(import.meta.url);

const dtsFile = DTSBuilder();

dtsFile.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

dtsFile.addModule('studiocms:plugins', {
	defaultExport: {
		typeDef: `import('${resolve('../config.js')}').SafePluginListType`,
	},
});

dtsFile.addModule('studiocms:plugin-helpers', {
	typeExports: [
		{
			name: 'SettingsField',
			typeDef: `import('${resolve('../plugins.js')}').SettingsField`,
		},
	],
});

export const pluginsDtsFileOutput = dtsFile.makeAstroInjectedType('plugins.d.ts');

export default pluginsDtsFileOutput;
