import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver } from 'astro-integration-kit';

const { resolve } = createResolver(import.meta.url);

const dtsFile = DTSBuilder();

dtsFile.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

dtsFile.addModule('studiocms:plugins', {
	defaultExport: {
		typeDef: `import('${resolve('../plugins.js')}').SafePluginListType`,
	},
});

dtsFile.addModule('studiocms:plugin-helpers', {
	typeExports: [
		{
			name: 'SettingsField',
			typeDef: `import('${resolve('../plugins.js')}').SettingsField`,
		},
		{
			name: 'SafePluginListType',
			typeDef: `import('${resolve('../plugins.js')}').SafePluginListType`,
		},
		{
			name: 'StudioCMSPlugin',
			typeDef: `import('${resolve('../plugins.js')}').StudioCMSPlugin`,
		},
		{
			name: 'StudioCMSPluginOptions',
			typeDef: `import('${resolve('../plugins.js')}').StudioCMSPluginOptions`,
		},
		{
			name: 'AvailableDashboardPages',
			typeDef: `import('${resolve('../plugins.js')}').AvailableDashboardPages`,
		},
		{
			name: 'FinalDashboardPage',
			typeDef: `import('${resolve('../plugins.js')}').FinalDashboardPage`,
		},
		{
			name: 'DashboardPage',
			typeDef: `import('${resolve('../plugins.js')}').DashboardPage`,
		},
	],
	namedExports: [
		{
			name: 'getPluginDashboardPages',
			typeDef: `import('${resolve('../lib/plugins/index.js')}').getPluginDashboardPages`,
		},
		{
			name: 'frontendNavigation',
			typeDef: `import('${resolve('../lib/plugins/index.js')}').frontendNavigation`,
		},
	],
});

export const pluginsDtsFileOutput = dtsFile.makeAstroInjectedType('plugins.d.ts');

export default pluginsDtsFileOutput;
