import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver } from 'astro-integration-kit';

// Create resolver relative to this file
const { resolve } = createResolver(import.meta.url);

// Import the Renderer Component
const RendererComponentTypes = resolve('../../static/components/Renderer.astro');

const renderer = DTSBuilder();

renderer.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

renderer.addModule('studiocms:renderer', {
	namedExports: [
		{
			name: 'StudioCMSRenderer',
			multiLineDescription: [
				'**StudioCMS Content Renderer component**',
				'',
				'@property {string} content - The content to render',
				'@example',
				'```astro',
				'---',
				"import { StudioCMSRenderer } from 'studiocms:renderer';",
				'---',
				'<StudioCMSRenderer content={content} />',
				'```',
			],
			typeDef: `typeof import('${RendererComponentTypes}').default`,
		},
	],
});

renderer.addModule('studiocms:renderer/current', {
	namedExports: [
		{
			name: 'contentRenderer',
			typeDef: `typeof import('${resolve('../renderer/contentRenderer.js')}').contentRenderer`,
		},
	],
	defaultExport: {
		typeDef: `typeof import('${resolve('../renderer/contentRenderer.js')}').default`,
	},
});

const rendererDTS = renderer.makeAstroInjectedType('renderer.d.ts');

export default rendererDTS;
