import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver } from 'astro-integration-kit';

const { resolve } = createResolver(import.meta.url);

const sdkDTS = DTSBuilder();

sdkDTS.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

sdkDTS.addModule('studiocms:sdk', {
	defaultExport: {
		typeDef: `typeof import('${resolve('../sdk/index.js')}').default`,
	},
});

sdkDTS.addModule('studiocms:sdk/types', {
	typeExports: [
		{
			name: 'STUDIOCMS_SDK',
			typeDef: `import('${resolve('../sdk/types/index.js')}').STUDIOCMS_SDK`,
		},
		// tableDefs
		{
			name: 'AvailableLists',
			typeDef: `import('${resolve('../sdk/types/index.js')}').AvailableLists`,
		},
		{
			name: 'CombinedRank',
			typeDef: `import('${resolve('../sdk/types/index.js')}').CombinedRank`,
		},
		{
			name: 'DatabaseTables',
			typeDef: `import('${resolve('../sdk/types/index.js')}').DatabaseTables`,
		},
		{
			name: 'PageContentReturnId',
			typeDef: `import('${resolve('../sdk/types/index.js')}').PageContentReturnId`,
		},
		{
			name: 'PageDataCategoriesInsertResponse',
			typeDef: `import('${resolve('../sdk/types/index.js')}').PageDataCategoriesInsertResponse`,
		},
		{
			name: 'PageDataReturnId',
			typeDef: `import('${resolve('../sdk/types/index.js')}').PageDataReturnId`,
		},
		{
			name: 'PageDataStripped',
			typeDef: `import('${resolve('../sdk/types/index.js')}').PageDataStripped`,
		},
		{
			name: 'PageDataTagsInsertResponse',
			typeDef: `import('${resolve('../sdk/types/index.js')}').PageDataTagsInsertResponse`,
		},
		{
			name: 'SingleRank',
			typeDef: `import('${resolve('../sdk/types/index.js')}').SingleRank`,
		},
		{
			name: 'SiteConfig',
			typeDef: `import('${resolve('../sdk/types/index.js')}').SiteConfig`,
		},
		// tsAliases
		{
			name: 'tsDiffTrackingInsert',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsDiffTrackingInsert`,
		},
		{
			name: 'tsDiffTrackingSelect',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsDiffTrackingSelect`,
		},
		{
			name: 'CombinedInsertContent',
			typeDef: `import('${resolve('../sdk/types/index.js')}').CombinedInsertContent`,
		},
		{
			name: 'tsOAuthAccountsSelect',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsOAuthAccountsSelect`,
		},
		{
			name: 'tsPageContentInsert',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsPageContentInsert`,
		},
		{
			name: 'tsPageContentSelect',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsPageContentSelect`,
		},
		{
			name: 'tsPageDataCategoriesInsert',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsPageDataCategoriesInsert`,
		},
		{
			name: 'tsPageDataCategoriesSelect',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsPageDataCategoriesSelect`,
		},
		{
			name: 'tsPageDataInsert',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsPageDataInsert`,
		},
		{
			name: 'tsPageDataSelect',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsPageDataSelect`,
		},
		{
			name: 'tsPageDataTagsInsert',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsPageDataTagsInsert`,
		},
		{
			name: 'tsPageDataTagsSelect',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsPageDataTagsSelect`,
		},
		{
			name: 'tsSiteConfigInsert',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsSiteConfigInsert`,
		},
		{
			name: 'tsSiteConfigSelect',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsSiteConfigSelect`,
		},
		{
			name: 'tsUsersInsert',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsUsersInsert`,
		},
		{
			name: 'tsUsersSelect',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsUsersSelect`,
		},
		{
			name: 'tsUsersUpdate',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsUsersUpdate`,
		},
		{
			name: 'tsPermissionsInsert',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsPermissionsInsert`,
		},
		{
			name: 'tsPermissionsSelect',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsPermissionsSelect`,
		},
		{
			name: 'tsSessionTableInsert',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsSessionTableInsert`,
		},
		{
			name: 'tsSessionTableSelect',
			typeDef: `import('${resolve('../sdk/types/index.js')}').tsSessionTableSelect`,
		},
		// Extras
		{
			name: 'GenericTable',
			typeDef: `import('${resolve('../sdk/types/index.js')}').GenericTable`,
		},
		{
			name: 'addDatabaseEntryInsertPage',
			typeDef: `import('${resolve('../sdk/types/index.js')}').addDatabaseEntryInsertPage`,
		},
		{
			name: 'CombinedUserData',
			typeDef: `import('${resolve('../sdk/types/index.js')}').CombinedUserData`,
		},
		{
			name: 'CombinedPageData',
			typeDef: `import('${resolve('../sdk/types/index.js')}').CombinedPageData`,
		},
		{
			name: 'DeletionResponse',
			typeDef: `import('${resolve('../sdk/types/index.js')}').DeletionResponse`,
		},
	],
});

sdkDTS.addModule('studiocms:sdk/cache', {
	defaultExport: {
		typeDef: 'STUDIOCMS_SDK_CACHE',
	},
	namedExports: [
		{
			name: 'studioCMS_SDK_Cache',
			typeDef: 'STUDIOCMS_SDK_CACHE',
		},
	],
	typeExports: [
		{
			name: 'STUDIOCMS_SDK_CACHE',
			typeDef: `import('${resolve('../sdk/cache.js')}').STUDIOCMS_SDK_CACHE`,
		},
		{
			name: 'PageDataCacheObject',
			typeDef: `import('${resolve('../sdk/cache.js')}').PageDataCacheObject`,
		},
		{
			name: 'SiteConfigCacheObject',
			typeDef: `import('${resolve('../sdk/cache.js')}').SiteConfigCacheObject`,
		},
		{
			name: 'VersionCacheObject',
			typeDef: `import('${resolve('../sdk/cache.js')}').VersionCacheObject`,
		},
	],
});

export const sdkDtsFile = sdkDTS.makeAstroInjectedType('sdk.d.ts');

export default sdkDtsFile;
