name: General Bug Report
description: File a general bug report.
title: "[Bug]: "
labels: ["bug"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is the bug report for?
      options:
        - studiocms
        - "@studiocms/auth0"
        - "@studiocms/blog"
        - "@studiocms/cloudinary-image-service"
        - "@studiocms/devapps"
        - "@studiocms/discord"
        - "@studiocms/github"
        - "@studiocms/google"
        - "@studiocms/html"
        - "@studiocms/markdoc"
        - "@studiocms/md"
        - "@studiocms/mdx"
        - "@studiocms/migrator"
        - "@studiocms/s3-storage"
        - "@studiocms/wysiwyg"
        - "@withstudiocms/auth-kit"
        - "@withstudiocms/buildkit"
        - "@withstudiocms/component-registry"
        - "@withstudiocms/config-utils"
        - "@withstudiocms/effect"
        - "@withstudiocms/internal_helpers"
        - "@withstudiocms/kysely"
        - "@withstudiocms/sdk"
        - "@withstudiocms/template-lang"
        - "N/A (describe in 'What happened?')"
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: 0.1.0-beta.0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
