name: Kysely SDK Issue
description: File a Kysely or SDK issue report.
title: "[Kysely SDK]: "
labels: ["kysely", "sdk"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Kysely SDK issue report!
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - Bug
        - Feature Request
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "An issue happened!"
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is the Kysely SDK issue report for?
      options:
        - "@withstudiocms/kysely"
        - "@withstudiocms/sdk"
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: 0.1.0-beta.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
