import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { defineUtility } from 'astro-integration-kit';

export const configDone = defineUtility('astro:config:done')(
	({ injectTypes }, imageComponentPath: string) => {
		const dtsFile = DTSBuilder();

		dtsFile.addSingleLineNote(
			'This file is generated by StudioCMS and should not be modified manually.'
		);

		dtsFile.addModule('studiocms:imageHandler/components', {
			namedExports: [
				{
					name: 'CustomImage',
					multiLineDescription: [
						'# Custom Image Component for StudioCMS:imageHandler',
						'',
						'This component will adapt to the current configuration of the StudioCMS image handler and will render the used image accordingly.',
						'',
						'@props {string} src - Image Source',
						'@props {string} alt - Image Alt',
						'@props {number} width - Image Width',
						'@props {number} height - Image Height',
					],
					typeDef: `typeof import('${imageComponentPath}').default`,
				},
			],
		});

		const dtsFileAstro = dtsFile.makeAstroInjectedType('imageHandler.d.ts');

		injectTypes(dtsFileAstro);
	}
);

export default configDone;
