import astroDTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver, defineUtility } from 'astro-integration-kit';
import type { Messages } from '../types';

const { resolve } = createResolver(import.meta.url);

export const configDone = defineUtility('astro:config:done')(
	({ injectTypes }, messages: Messages) => {
		// Make DTS file for StudioCMS Plugins Virtual Module
		const dtsFile = astroDTSBuilder();

		dtsFile.addSingleLineNote(
			'This file is auto-generated by StudioCMS and should not be modified.'
		);

		dtsFile.addModule('studiocms:plugins', {
			defaultExport: {
				typeDef: `import('${resolve('../index.ts')}').SafePluginListType`,
			},
		});

		dtsFile.addModule('studiocms:changelog', {
			defaultExport: {
				typeDef: 'string',
			},
		});

		// Inject the DTS file
		injectTypes(dtsFile.makeAstroInjectedType('plugins.d.ts'));

		// Log Setup Complete
		messages.push({
			label: 'studiocms:setup',
			logLevel: 'info',
			message: 'Setup Complete. 🚀',
		});
	}
);

export default configDone;
