FROM mcr.microsoft.com/devcontainers/typescript-node:dev-22-bookworm@sha256:71fd4b88989b8233b1ef8cdf3d99fe614bbabf1bfb974795204df602f5835fcc

# Copy welcome message
COPY welcome-message.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt
