FROM mcr.microsoft.com/devcontainers/typescript-node:dev-22-bookworm@sha256:3b14a0c25fc949d08dd398fe865e37568cb38f4853df632dd6592790ee9d03bb

# Copy welcome message
COPY welcome-message.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt
