FROM mcr.microsoft.com/devcontainers/typescript-node:dev-22-bookworm@sha256:76793db91ec292f79e92c1de5df9d7359d6534b423af059f8a63a365de398f30

# Copy welcome message
COPY welcome-message.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt
