import type { RequiredGrapesBlocksOptions } from './types.js';

export const cmdImport = 'gjs-open-import-webpage';
export const cmdDeviceDesktop = 'set-device-desktop';
export const cmdDeviceTablet = 'set-device-tablet';
export const cmdDeviceMobile = 'set-device-mobile';
export const exportTemplate = 'export-template';
export const cmdClear = 'canvas-clear';
export const cmdSave = 'store-data';
export const typedId = 'typed';
export const typedTraitStringId = 'typed-strings';

export const defaultGrapesBlocksOptions: RequiredGrapesBlocksOptions = {
	blocks: [
		'link-block',
		'quote',
		'text-basic',
		'tooltip',
		'typed',
		'column1',
		'column2',
		'column3',
		'column3-7',
		'text',
		'link',
		'image',
		'video',
		'map',
		'countdown',
	],
	block: () => ({}),
	modalImportTitle: 'Import',
	modalImportButton: 'Import',
	modalImportLabel: '',
	modalImportContent: '',
	importViewerOptions: {},
	textCleanCanvas: 'Are you sure you want to clear the canvas?',
	showStylesOnChange: true,
	flexGrid: true,
	stylePrefix: 'gjs-',
	addBasicStyle: true,
	labelColumn1: '1 Column',
	labelColumn2: '2 Columns',
	labelColumn3: '3 Columns',
	labelColumn37: '2 Columns 3/7',
	labelText: 'Text',
	labelLink: 'Link',
	labelImage: 'Image',
	labelVideo: 'Video',
	labelMap: 'Map',
	rowHeight: 75,
	tooltip: {
		id: 'tooltip',
		labelTooltip: 'Tooltip',
		blockTooltip: {},
		propsTooltip: {},
		extendTraits: (traits) => traits,
		attrTooltip: 'data-tooltip',
		classTooltip: 'tooltip-component',
		style: '',
		styleAdditional: '',
		privateClasses: true,
		stylableTooltip: [
			'background-color',
			'padding',
			'padding-top',
			'padding-right',
			'padding-bottom',
			'padding-left',
			'font-family',
			'font-size',
			'font-weight',
			'letter-spacing',
			'color',
			'line-height',
			'text-align',
			'border-radius',
			'border-top-left-radius',
			'border-top-right-radius',
			'border-bottom-left-radius',
			'border-bottom-right-radius',
			'border',
			'border-width',
			'border-style',
			'border-color',
		],
		showTooltipOnStyle: true,
	},
	typed: {
		script: 'https://cdn.jsdelivr.net/npm/typed.js@2.0.11',
		block: {},
		props: (p) => p,
	},
	rteOpts: {},
	countdown: {
		id: 'countdown',
		label: 'Countdown',
		block: {},
		props: {},
		style: '',
		styleAdditional: '',
		startTime: '',
		endText: 'EXPIRED',
		dateInputType: 'date',
		labelDays: 'days',
		labelHours: 'hours',
		labelMinutes: 'minutes',
		labelSeconds: 'seconds',
		classPrefix: 'countdown',
	},
};
