name: Generate Code Coverage Report and Upload
description: This action generates a code coverage report from test results and upload to Codecov.

inputs:
  slug:
    description: "The repository slug for Codecov (e.g., owner/repo)."
    required: true
    default: "withstudiocms/studiocms"
  coverage_flags:
    description: "Flags to categorize the coverage report."
    required: false
    default: "integrations,plugins,tools-utils"
  codecov_token:
    description: "The Codecov upload token."
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
      if: always() && (github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main')
      with:
        slug: ${{ inputs.slug }}
        directory: "./coverage/"
        files: "./coverage-final.json"
        flags: ${{ inputs.coverage_flags }}
        token: ${{ inputs.codecov_token }}

    - name: Upload test results to Codecov
      uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3
      if: always() && (github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main')
      with:
        slug: ${{ inputs.slug }}
        files: "./junit-report.xml"
        flags: ${{ inputs.coverage_flags }}
        token: ${{ inputs.codecov_token }}
