import astroDTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver } from 'astro-integration-kit';

const { resolve } = createResolver(import.meta.url);

const DTSFile = astroDTSBuilder();

DTSFile.addSingleLineNote(
	'// This file is auto-generated by StudioCMS and should not be modified.'
);

DTSFile.addModule('studiocms:plugins', {
	defaultExport: {
		typeDef: `import('${resolve('./types')}').SafePluginListType`,
	},
});

export const stubs = DTSFile.makeAstroInjectedType('plugins.d.ts');
