import astroDTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver } from 'astro-integration-kit';

const { resolve } = createResolver(import.meta.url);

export function generateStubs() {
	const DTSFile = astroDTSBuilder();

	DTSFile.addSingleLineNote(
		'// This file is auto-generated by StudioCMS and should not be modified.'
	);

	DTSFile.addModule('studiocms:plugins', {
		defaultExport: {
			typeDef: `import('${resolve('./types')}').SafePluginListType`,
		},
	});

	return DTSFile.makeAstroInjectedType('plugins.d.ts');
}
