import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver } from 'astro-integration-kit';

const { resolve } = createResolver(import.meta.url);

const authScripts = DTSBuilder();

authScripts.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

authScripts.addModule('studiocms:auth/scripts/three', {
	defaultExport: {
		typeDef: 'any',
		multiLineDescription: [
			'This module should be imported within a script tag.',
			'@example <script>import "studiocms:auth/scripts/three";</script>',
		],
	},
});

authScripts.addModule('studiocms:auth/scripts/formListener', {
	namedExports: [
		{
			name: 'formListener',
			typeDef: `typeof import('${resolve('../scripts/formListener.js')}').formListener`,
		},
	],
});

const dtsFile = authScripts.makeAstroInjectedType('auth-scripts.d.ts');

export default dtsFile;
