import DTSBuilder from '@matthiesenxyz/astrodtsbuilder';
import { createResolver } from 'astro-integration-kit';

const { resolve } = createResolver(import.meta.url);

const authUtils = DTSBuilder();

authUtils.addSingleLineNote(
	'This file is generated by StudioCMS and should not be modified manually.'
);

authUtils.addModule('studiocms:auth/utils/authEnvCheck', {
	namedExports: [
		{
			name: 'authEnvCheck',
			typeDef: `typeof import('${resolve('../utils/authEnvCheck.ts')}').authEnvCheck`,
		},
	],
});

const dtsFile = authUtils.makeAstroInjectedType('auth-utils.d.ts');

export default dtsFile;
