name: CI - Translation Changesets

on:
  pull_request:
    types: [labeled, synchronize]

permissions:
  contents: write

jobs:
  build-translation-changesets:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'translations') && github.event.pull_request.user.login == 'studiocms-no-reply'
    steps:
      - name: Generate a token
        id: bot-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.STUDIOCMS_GIT_BOT_APP_ID }}
          private-key: ${{ secrets.STUDIOCMS_GIT_BOT_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: true
          ref: ${{ github.head_ref }}
          token: ${{ steps.bot-token.outputs.token }}

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@885437ef4376e64fc295161092b8a165bc5efd39 # main

      - name: Create Translation Changesets
        run: node .github/scripts/translation-changeset.mjs
        env:
          CI_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
    
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_message: '[ci] changesets'
          branch: ${{ github.head_ref }}
          commit_user_name: studiocms-no-reply
          commit_user_email: no-reply@studiocms.dev
          commit_author: StudioCMS <no-reply@studiocms.dev>
