name: CI - Crowdin Sync PR

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - file-fully-translated
      - file-fully-reviewed
      - file-added
      - file-updated
      - file-reverted
      - file-deleted

permissions:
  contents: write
  pull-requests: write

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.STUDIOCMS_SERVICE_TOKEN }}

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_main
          create_pull_request: true
          pull_request_title: 'feat(i18n): Crowdin Translation Sync'
          pull_request_body: 'Merge this PR to sync with Crowdin'
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.STUDIOCMS_SERVICE_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
