name: Build and deploy playground

on:
  push:
    branches:
      - main
      - tweak-dockerfile # temp for testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./playground.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/studiocms-playground:latest
          platforms: linux/amd64
          build-args: |
            ASTRO_DB_REMOTE_URL=${{ secrets.ASTRO_DB_REMOTE_URL }}
            ASTRO_DB_APP_TOKEN=${{ secrets.ASTRO_DB_APP_TOKEN }}
            CMS_ENCRYPTION_KEY=${{ secrets.CMS_ENCRYPTION_KEY }}
