name: Translation Changesets

on:
  pull_request:
    types: [labeled, synchronize]

permissions:
  contents: write

jobs:
  build-translation-changesets:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'translations') && github.event.pull_request.user.login == 'studiocms-no-reply'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            persist-credentials: false
            ref: ${{ github.head_ref }}
            token: ${{ secrets.STUDIOCMS_SERVICE_TOKEN }}

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@4202f6901825c1e837677402a7508132103ea792 # main Jul 17th, 2025

      - name: Create Translation Changesets
        run: pnpm ci:translations:changeset
        env:
          CI_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
    
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_message: '[ci] changesets'
          branch: ${{ github.head_ref }}
          commit_user_name: studiocms-no-reply
          commit_user_email: no-reply@studiocms.dev
          commit_author: StudioCMS <no-reply@studiocms.dev>