name: CI - Pkg-pr-new

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: true
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  preview-main:
    name: Continuous Deployment Snapshot
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/preview.yml@729a20ff5e68dd95330fb1914b801960ad4b5e7b # main
    with:
      build-cmd: "pnpm ci:build"

  preview-changeset-release:
    name: Pre-Release Snapshot
    if: github.event_name == 'pull_request' && (github.event.pull_request.user.login == 'studiocms-no-reply' || github.event.pull_request.user.login == 'apollo-git-bot[bot]')
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/preview.yml@729a20ff5e68dd95330fb1914b801960ad4b5e7b # main
    with:
      build-cmd: "pnpm ci:build"

  preview-pr:
    name: PR Snapshot Preview
    if: github.event_name == 'pull_request' && (github.event.pull_request.user.login != 'studiocms-no-reply' && github.event.pull_request.user.login != 'apollo-git-bot[bot]') && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/preview-pr.yml@729a20ff5e68dd95330fb1914b801960ad4b5e7b # main
    with:
      build-cmd: "pnpm ci:build"
