name: CI - Lunaria Overview Generation on PRs

on:
  pull_request_target:
    types: [opened, synchronize]
    branches: 
      # - main
      # TODO: Remove issue-304 from the list of branches and enable main once PR#333 is ready to merged
      - issue-304

jobs:
  lunaria-overview:
    name: Generate Lunaria Overview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.STUDIOCMS_SERVICE_TOKEN }}

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@main

      - name: Generate Lunaria Overview
        uses: lunariajs/action@astro-docs
        with:
          working-directory: www/docs
          token: ${{ secrets.STUDIOCMS_SERVICE_TOKEN }}