name: CI - Translation Report Bot

on:
  schedule:
    - cron: '0 10 * * TUE'
  workflow_dispatch:

jobs:
  translation:
    name: translation_report
    if: ${{ github.repository_owner == 'withstudiocms' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@main

      - id: message
        name: Format Discord message
        run: pnpm ci:crowdin:bot
        env:
          WORKFLOW_DISPATCH: ${{ github.event_name == 'workflow_dispatch' }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Send a Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_I18N_REPORT }}
        uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554 # 0.4.0
        with:
          args: "${{ steps.message.outputs.DISCORD_MESSAGE }}"
