name: StudioCMS Deployments

on: 
  pull_request_target:
    types: [assigned, opened, reopened]

permissions:
  pull-requests: write
  
jobs:
  deploymentmessage:
    name: Send deployment links
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Queued Comment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          github-token: ${{ secrets.STUDIOCMS_SERVICE_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Thank you for submitting your Pull Request, the following links will become available for preview shortly:\n
              - [StudioCMS Documentation](https://pr${context.payload.pull_request.number}.docs.studiocms.dev/)\n
              - [StudioCMS Demo (node-playground)](https://pr${context.payload.pull_request.number}.demo.studiocms.dev/) (Also deployed with package changes)\n
              - [StudioCMS Ui Demo (ui-playground)](https://pr${context.payload.pull_request.number}.ui-testing.studiocms.dev/)`
            })
